### PR TITLE
appengine_api: prevent crashes when updating metadata or aliases

### LINKED ISSUE #357: Do not crash when using "" as alias name or value
"" should be handled as invalid, instead of crashing. Also metadata should be checked for similar issues (empty string key should not be allowed, while empty string value is fine for metadata).

### PR DESCRIPTION
**Pull request by matt-mazzucato**
+ Do not crash when using an empty string for aliases (either key or
value). 400 is returned instead.
+ Do not crash when using an empty string for metadata keyi. 400 is
returned instead.
+ Metadata values can be set to empty string.

Fix #357

### CODE REVIEW

File: apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex [hunk 1]
```diff
@@ -84,11 +84,27 @@ defmodule Astarte.AppEngine.API.Device do
...
+
+      {:error, :invalid_metadata} ->
+        {:error, :invalid_metadata}
+
+      {:error, :alias_already_in_use} ->
+        {:error, :alias_already_in_use}
+
+      error ->
+        error
     end
```
Comment (rbino) [inline apps/astarte_appengine_api/lib/astarte_appengine_api/device/device.ex:99]: You're catching 3 special cases and returning them as-is, then you have a generic case that you also return as-is. Might as well drop the `else` completely since it will fall-through anyway

File: apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_controller.ex [hunk 2]
```diff
@@ -54,6 +54,15 @@ defmodule Astarte.AppEngine.APIWeb.DeviceStatusController do
...
         render(conn, "show.json", device_status: device_status)
+      else
+        {:error, :invalid_alias} ->
+          {:error, :invalid_alias}
+
+        {:error, :invalid_metadata} ->
+          {:error, :invalid_metadata}
+
+        error ->
+          error
```
Comment (rbino) [inline apps/astarte_appengine_api/lib/astarte_appengine_api_web/controllers/device_status_controller.ex:65]: Same here
