### PR TITLE
Fix pretty log

### LINKED ISSUE #121: Add pretty_log to astarte_trigger_engine
astarte_trigger_engine should start using pretty_log as log formatter.
Contextually logger metadata should be used and all log levels reviewed.
All http response with a http code != 200 must be carefully logged, including information about the source event.

### PR DESCRIPTION
**Pull request by matt-mazzucato**
Add pretty_log to app_engine_api, data_updater_plant, pairing_api, realm_management and realm_management_api.
Update pretty_log configuration for the other apps.
Fix #121, #164, #161, #133

### CODE REVIEW

File: apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/application.ex [hunk 1]
```diff
@@ -25,6 +25,9 @@ defmodule Astarte.Housekeeping.API.Application do
   # for more information on OTP Applications
   def start(_type, _args) do
     import Supervisor.Spec
+    require Logger
```
Comment (rbino) [inline apps/astarte_housekeeping_api/lib/astarte_housekeeping_api/application.ex]: This goes outside the `def`

File: apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex [hunk 2]
```diff
@@ -26,6 +26,9 @@ defmodule Astarte.AppEngine.API.Application do
     alias Astarte.AppEngine.API.Config
 
     import Supervisor.Spec
+    require Logger
```
Comment (rbino) [inline apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex]: This goes outside the `def`

File: apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex [hunk 3]
```diff
@@ -26,6 +26,9 @@ defmodule Astarte.AppEngine.API.Application do
...
+
+    Logger.info("Starting application.", tag: "app_engine_api_start")
```
Comment (rbino) [inline apps/astarte_appengine_api/lib/astarte_appengine_api/application.ex]: `appengine`

File: apps/astarte_pairing_api/lib/astarte_pairing_api/application.ex [hunk 4]
```diff
@@ -28,6 +28,9 @@ defmodule Astarte.Pairing.API.Application do
     Metrics.PipelineInstrumenter.setup()
     Metrics.PrometheusExporter.setup()
 
+    import Logger
```
Comment (rbino) [inline apps/astarte_pairing_api/lib/astarte_pairing_api/application.ex]: It's `require Logger`, and it goes outside the def

File: apps/astarte_realm_management_api/lib/astarte_realm_management_api/application.ex [hunk 5]
```diff
@@ -24,6 +24,10 @@ defmodule Astarte.RealmManagement.API.Application do
   # See http://elixir-lang.org/docs/stable/elixir/Application.html
   # for more information on OTP Applications
   def start(_type, _args) do
+    require Logger
```
Comment (rbino) [inline apps/astarte_realm_management_api/lib/astarte_realm_management_api/application.ex]: This goes on top
