### PR TITLE
RM: do not fail to delete device if there are no individual interfaces

### LINKED ISSUE #885: Unable to delete device when no interfaces are present in the realm
It seems that devices cannot be deleted from an Astarte realm when no interfaces are present in the realm.

Steps to reproduce:
1. Follow the [Astarte in 5 minutes](https://docs.astarte-platform.org/astarte/latest/010-astarte_in_5_minutes.html) guide to setup a local Astarte instance via docker compose, with a `test` realm in it.
2. Only create the realm and avoid installing other resources from the guide.
3. Register a new device on the Astarte realm.
4. Attempt to delete the device via an HTTP DELETE on Realm Management, as described in #816
5. Realm Management correctly accepts the request, but the device never gets deleted.

Here are some relevant logs from Realm Management:
```
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:16:25.835+00:00 msg="Added device fVjW5ZscQI6u1P-eoDO1jg to deletion in progress" realm=test module=Astarte.RealmManagement.Engine function=delete_device/2
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:19:55.234+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:19:55.235+00:00 msg="Task #PID<0.2383.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:19:55.236+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:19:55.237+00:00 msg="Task #PID<0.2384.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:19:55.237+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:19:55.238+00:00 msg="Task #PID<0.2385.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:19:55.238+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:19:55.239+00:00 msg="Task #PID<0.2386.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:24:55.260+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:24:55.261+00:00 msg="Task #PID<0.2520.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:24:55.262+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:24:55.264+00:00 msg="Task #PID<0.2521.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:24:55.265+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:24:55.266+00:00 msg="Task #PID<0.2522.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:24:55.266+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:24:55.267+00:00 msg="Task #PID<0.2523.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:29:55.287+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:29:55.288+00:00 msg="Task #PID<0.2628.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:29:55.289+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:29:55.290+00:00 msg="Task #PID<0.2629.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:29:55.291+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:29:55.292+00:00 msg="Task #PID<0.2630.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:29:55.292+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:29:55.293+00:00 msg="Task #PID<0.2631.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:34:55.312+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:34:55.313+00:00 msg="Task #PID<0.2735.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:34:55.314+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:34:55.315+00:00 msg="Task #PID<0.2736.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:34:55.317+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:34:55.318+00:00 msg="Task #PID<0.2737.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:34:55.318+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:34:55.319+00:00 msg="Task #PID<0.2738.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:39:55.338+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:39:55.339+00:00 msg="Task #PID<0.2843.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:39:55.340+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:39:55.341+00:00 msg="Task #PID<0.2844.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:39:55.341+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:39:55.342+00:00 msg="Task #PID<0.2845.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:39:55.343+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:39:55.344+00:00 msg="Task #PID<0.2846.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:44:55.364+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:44:55.366+00:00 msg="Task #PID<0.2950.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:44:55.367+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:44:55.368+00:00 msg="Task #PID<0.2951.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:44:55.368+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:44:55.369+00:00 msg="Task #PID<0.2952.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:44:55.370+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:44:55.371+00:00 msg="Task #PID<0.2953.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:49:55.386+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:49:55.387+00:00 msg="Task #PID<0.3058.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:49:55.387+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:49:55.388+00:00 msg="Task #PID<0.3059.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:49:55.389+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:49:55.390+00:00 msg="Task #PID<0.3060.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:49:55.390+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:49:55.391+00:00 msg="Task #PID<0.3061.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:54:55.408+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:54:55.409+00:00 msg="Task #PID<0.3165.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:54:55.410+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:54:55.411+00:00 msg="Task #PID<0.3166.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:54:55.412+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:54:55.413+00:00 msg="Task #PID<0.3167.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:54:55.413+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:54:55.414+00:00 msg="Task #PID<0.3168.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:59:55.431+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:59:55.432+00:00 msg="Task #PID<0.3278.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:59:55.433+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:59:55.434+00:00 msg="Task #PID<0.3279.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:59:55.435+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:59:55.436+00:00 msg="Task #PID<0.3280.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"
astarte-astarte-realm-management-1  | level=info ts=2023-12-12T15:59:55.437+00:00 msg="Starting to remove device fVjW5ZscQI6u1P-eoDO1jg" module=Astarte.RealmManagement.DeviceRemoval.DeviceRemover function=run/1 tag=device_delete_start
astarte-astarte-realm-management-1  | level=error ts=2023-12-12T15:59:55.438+00:00 msg="Task #PID<0.3281.0> started from Astarte.RealmManagement.DeviceRemoval.Scheduler terminating\n** (Xandra.Error) unconfigured table individual_datastreams\n    (xandra 0.14.0) lib/xandra.ex:596: Xandra.prepare!/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/queries.ex:1844: Astarte.RealmManagement.Queries.do_retrieve_individual_datastreams_keys!/3\n    (db_connection 2.4.2) lib/db_connection.ex:775: DBConnection.run/3\n    (astarte_realm_management 1.2.0-dev) lib/astarte_realm_management/device_removal/device_remover.ex:39: Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    (elixir 1.15.7) lib/task/supervised.ex:101: Task.Supervised.invoke_mfa/2\nFunction: &Astarte.RealmManagement.DeviceRemoval.DeviceRemover.run/1\n    Args: [%{device_id: <<125, 88, 214, 229, 155, 28, 64, 142, 174, 212, 255, 158, 160, 51, 181, 142>>, realm_name: \"test\", vmq_ack: true, dup_start_ack: true, dup_end_ack: true}]"

```

### PR DESCRIPTION
**Pull request by Annopaolo**
Device deletion was stuck in a loop when `individual_datastreams` and `individual_properties` tables were still not configured. Add a check for the presence of the two tables before trying to delete data from them. If they are not configured, move on.

Closes #885 .

### CODE REVIEW

**Review by rbino — APPROVED** [review]

File: apps/astarte_realm_management/lib/astarte_realm_management/queries.ex [hunk 1]
```diff
@@ -1711,6 +1711,29 @@ defmodule Astarte.RealmManagement.Queries do
     end
   end
 
+  def does_table_exist?(realm_name, table_name) do
```
Comment (rbino) [inline apps/astarte_realm_management/lib/astarte_realm_management/queries.ex:1714]: The convention in Elixir is not using the auxiliary verb when using `?`, so this should be `table_exists?`.

Moreover imho the `do_table_exists?` is small enough (and the resulting name is ugly enough) that you can just put the implementation inside the lambda here instead of having a separate function

**Review by rbino — CHANGES_REQUESTED** [review]

File: apps/astarte_realm_management/lib/astarte_realm_management/queries.ex (hunk 1 above)
Comment (Annopaolo) [reply apps/astarte_realm_management/lib/astarte_realm_management/queries.ex]: Done

File: apps/astarte_realm_management/lib/astarte_realm_management/queries.ex [hunk 2]
```diff
@@ -1711,6 +1711,27 @@ defmodule Astarte.RealmManagement.Queries do
...
+        WHERE keyspace_name = :keyspace_name
+        AND table_name = :table_name
+        """
+
+        params = %{keyspace_name: realm_name, table_name: table_name}
+
+        prepared = Xandra.prepare!(conn, statement)
+        page = Xandra.execute!(conn, prepared, params)
+        [%{count: table_count}] = Enum.to_list(page)
+        if table_count != 0, do: true, else: false
```
Comment (rbino) [inline apps/astarte_realm_management/lib/astarte_realm_management/queries.ex:1730]: This line can just be `table_count != 0`

**Review by rbino — CHANGES_REQUESTED** [review]

**Review by rbino — APPROVED** [review]
